# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: IDM.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'IDM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tIDM.proto\x12\x03idm\":\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06parola\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\t\">\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"=\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06parola\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\t\"A\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2u\n\nIDMService\x12.\n\x05Login\x12\x11.idm.LoginRequest\x1a\x12.idm.LoginResponse\x12\x37\n\x08Register\x12\x14.idm.RegisterRequest\x1a\x15.idm.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IDM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=18
  _globals['_LOGINREQUEST']._serialized_end=76
  _globals['_LOGINRESPONSE']._serialized_start=78
  _globals['_LOGINRESPONSE']._serialized_end=140
  _globals['_REGISTERREQUEST']._serialized_start=142
  _globals['_REGISTERREQUEST']._serialized_end=203
  _globals['_REGISTERRESPONSE']._serialized_start=205
  _globals['_REGISTERRESPONSE']._serialized_end=270
  _globals['_IDMSERVICE']._serialized_start=272
  _globals['_IDMSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
